# This is a basic workflow to help you get started with Actions

name: Zip Files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'febe_cm_markers.zip'
          exclusions: 'LICENSE README.md *.github* *.git*'

      - uses: actions/upload-artifact@v4
        with:
          name: haskha-timers
          path: ${{ github.workspace }}/febe_cm_markers.zip
          compression-level: 0
